name: depend
description: "depend simplifies dependency management in Flutter apps, providing easy initialization and access to services across the widget tree."
version: 5.0.1

homepage: https://www.contributors.info/repository/depend

repository: https://github.com/AlexHCJP/depend

issue_tracker: https://github.com/AlexHCJP/depend/issues

topics:
  - dependency
  - injection
  - dependency-injection
  - service
  - dependency-management

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mocktail: ^1.0.4
