name: depend
description: "Dependencies is a library for managing dependencies in Flutter applications. It provides a convenient way to initialize and access services or repositories via an InheritedWidget."
version: 2.0.3

homepage: https://www.contributors.info/repository/depend

repository: https://github.com/AlexHCJP/depend

issue_tracker: https://github.com/AlexHCJP/depend/issues

topics:
  - dependency
  - injection
  - dependency-injection
  - service
  - dependency-management

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
